FROM openjdk:11.0
VOLUME /tmp
ADD target/FundManagement-0.0.1-SNAPSHOT.jar app.jar

RUN sh -c 'echo spring.datasource.url=jdbc:mysql://mysql:3306/mydb > application.properties'
RUN sh -c 'echo spring.datasource.username=root    >> application.properties'
RUN sh -c 'echo spring.datasource.password= >> application.properties'

ENTRYPOINT ["java","-jar","/app.jar"]
